name = "hotbox"
version = "0.1.1"

description = "Improve software performance by moving as much of a directory's contents to a ramdisk as possible"
licences = ["Unlicense"]
repository = { type = "github", user = "lara-ah-ah-ah", repo = "hotbox" }

# full reference: https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
dynamic = ">= 0.1.2 and < 1.0.0"
gleeunit = ">= 1.3.1 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
