// This is a codex autogenerated file. Do not edit it manually, it will be overwritten.

pub const name = "hotbox"

pub const version = "0.2.0"

pub const description = "Improve software performance by moving as much of a directory's contents to a ramdisk as possible"
