// This is a codex autogenerated file. Do not edit it manually, it will be overwritten.

pub const name = "hotbox"

pub const version = "0.1.0"

pub const description = "Improve software performance by moving as much of a directories contents to a ramdisk"
